name: AWSCodeBuild Demo

on:
  workflow_dispatch:

jobs:
  GH-To-AWS-CodeBuild-Integratio-Test:
    runs-on:
      - codebuild-smTestWithVPC-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: | 
          echo "Hello World!"
          echo "First Build from GitHub action workflow By - Satish M."
          pwd; ls -la
          cat /etc/os-release
          touch "efsTest.txt"; echo "A Sample file to write on EFS" > efsTest.txt
          pwd; ls -la; cat "efsTest.txt"
