name: AWSCodeBuild Demo

on:
  workflow_dispatch:

jobs:
  GH-To-AWS-CodeBuild-Integratio-Test:
    runs-on:
      - codebuild-smTestWithVPC-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3      
      - name: Build Code
        run: |
          pwd; ls -la
          find /efs
          cd ${{ github.workspace }}
          pwd; ls -la
          python3 test.py >> /efs/efsTest.txt
          cat /efs/efsTest.txt
          cd /efs; mkdir -p gh-runners/quic-yocto/kas-mirrors
          find /efs
          
      - name: GithubVariable
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
