name: AWSCodeBuild Demo

on:
  workflow_dispatch:

jobs:
  GH-To-AWS-CodeBuild-Integratio-Test:
    runs-on:
      - codebuild-sm-aws-gh-demo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: | 
          echo "Hello World!"
          echo "First Build from GitHub action workflow By - Satish M."
          pwd; ls -la
          cat /etc/os-release
          cd /ghdemo
          pwd; ls -la
          touch "efsTest.txt"; echo "EFS Test" > efsTest.txt 
          ls -la
