name: AWSCodeBuild Demo

on:
  workflow_dispatch:

jobs:
  GH-To-AWS-CodeBuild-Integratio-Test:
    runs-on:
      - codebuild-smTestWithVPC-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build Code
        run: |
          cd $ {{env.CODEBUILD_SRC_DIR}}
          pwd; ls -la
          python3 test.py >> /efs/efsTest.txt 2&>1          
          cat /efs/efsTest.txt
