name: AWSCodeBuild Demo

on:
  workflow_dispatch:

jobs:
  GH-To-AWS-CodeBuild-Integratio-Test:
    runs-on:
      - codebuild-smTestWithVPC-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout Code
        uses:
          actions/checkout@v3
          aws-actions/aws-codebuild-run-build@v1
        
      - name: Build Code
        run:
          pwd; ls -la          
          cd ${{ env.CODEBUILD_SRC_DIR }}
          python3 test.py >> /efs/efsTest.txt
          cat /efs/efsTest.txt
