name: AWSCodeBuild Demo

on:
  workflow_dispatch:

jobs:
  GH-To-AWS-CodeBuild-Integratio-Test:
    runs-on:
      - codebuild-smTestWithVPC-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3      
      - name: Build Code
        run: |
          id
          sudo su codebuild-user
          id
          which sudo
          
      - name: GithubVariable
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
